petra:
  kafka:
    servers: localhost:29092
  thread:
    count: 4

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.88:5432/petradb
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: false
#    show-sql: true
#    entityManagerFactory:
#      name: my-persistence-unit
#    hibernate:
#      ddl-auto: none
#      format_sql: true
#      generate_statistics: true
#    transaction:
#      manager-name: jpaTransactionManager
